# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66d6513faa0ea537e597e48a48a924a1297f8f31e1623bcde8df0f3c7ad5153d496fa8d15091c5e6e51bbc924627f8a274c29c10a4c1a7429443dfa4b3e732fa

test:
  secret_key_base: 7fac9feb8df82b11dbf40b7691521c9de878412c314e2b2d52bd2e27ab4da01d6e9a58c5aded779810125a74c40675c4ca8e064fc95cf1ff88fa2a3a9c13704f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
